language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - composer install
  - vendor/unb-libraries/dockworker/scripts/travis/init.sh

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: rp+M/ff7/cehjSe6pyjdSMusmuhI2gkx0j83ICmPgBP3wEzrq8Qy8GF2oLMAdmHs0809VF/XaxYybPdpVmDFAhFJbjqmSaLZSjTJATQC222ceJeecEVrjkcWGe5RATzv7qruODU+s+vX093r/WoBNhVwrmGRa2PJiqILBPtB3E0+89qtLydKqfEbOd0rBnEdM3aGmWMVUEIPtzG/Axt3YeTEqrfs2kUlILukhwIi4bhKL611OkbJL919bH0CpJxaNkuiXk05Xd9hZ1OghMblKRFI4QKUpNEvvyibAq18FjWfJ5hCokqlG1TlyLkubb2o2KcjeZ7roh6yy2pZZcxyvmhP5Dc1efWz7MYIEljhAb++jfwkPJmn0Sj9/WIgqjo5YSI0Ct6GPtlkOpcOqfq3nzQwlFhSuzlilfEizbTV+mWOMKE2CeuGI2OV6NWoy+56qw9m36219K/59FZIrJAETrfy/GXRfsVWuR+aZmsFjQCIHFe/S3fUZvxpL4hiLZyyqL4zU26Zde26LttucYJAwxn9GOt0r5HPVpzhKfv/XrcU8vdRXdDEggDZfNQMpS1Dxzz68JDxlX07+KXC3su/L36jIHB8l5VBWKdiNfhAnPWH2+QdzshFgFQ0vFfaxJpBJdo32XNmXInDErARZdlsmNS8mdgUWfZz/IzBwthSx28=
    on_start: always
    on_success: always
