apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
    appMajor: "5"
    instance: mediawiki.mysql.lib.unb.ca
    tier: database
    uri: mediawiki.mysql.lib.unb.ca
    vcsOwner: unb-libraries
    vcsRepository: mysql.lib.unb.ca
    vcsRef: prod
  name: mediawiki-mysql-lib-unb-ca
  namespace: prod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        appMajor: "5"
        instance: mediawiki.mysql.lib.unb.ca
        tier: database
        uri: mediawiki.mysql.lib.unb.ca
        vcsOwner: unb-libraries
        vcsRepository: mysql.lib.unb.ca
        vcsRef: prod
    spec:
      containers:
        -
          env:
            -
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: root-password
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          name: mediawiki-mysql-lib-unb-ca
          ports:
            -
              containerPort: 3306
              name: mysql
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      priorityClassName: vip-essential
      imagePullSecrets:
        -
          name: docker-hub-auth
      restartPolicy: Always
      volumes:
        -
          name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mediawiki-mysql-lib-unb-ca
